name: Docker build and run test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Docker build
        run: docker build -t communitybot .
      
      - name: Docker run
        run: docker run -d -p 443:443 -v /home/me/app/db:/app/db --name communitybot-container communitybot
      
      - name: Waiting start
        run: sleep 10s && docker logs communitybot-container
      
      - name: Check run status code
        run: sh -c '[ $(curl -k -o -I -L -s -w "%{http_code}" http://localhost:80) -eq 200 ]'
      
      - name: Check run
        run: curl -k -o - https://localhost:443
